---
- name: Configure Loopback interface and verify
  hosts: routers
  gather_facts: no

  tasks:
    - name: Configure IP on Loopback10
      cisco.ios.ios_config:
        lines:
          - interface Loopback10
          - ip address 4.4.4.4 255.255.255.0
          - no shutdown

    - name: Save running-config to startup-config
      cisco.ios.ios_command:
        commands:
          - write memory

    - name: Verify interface brief status
      cisco.ios.ios_command:
        commands:
          - show ip int br
      register: result

    - name: Show Loopback10 config
      ansible.builtin.debug:
        var: result.stdout_lines
