---
- name: Backup show version
  hosts: all
  gather_facts: no

  tasks:
    - name: Run 'show version' on Cisco device
      cisco.ios.ios_command:
        commands: show version
      register: output

    - name: Debug print output
      ansible.builtin.debug:
        var: output.stdout_lines

    - name: Save output to file
      ansible.builtin.copy:
        content: "{{ output.stdout_lines }}"
        dest: "./output/{{ inventory_hostname }}.txt"
