---
- name: Run multiple IOS commands using ios_command
  hosts: routers
  gather_facts: no

  tasks:
    - name: Run multiple commands
      cisco.ios.ios_command:
        commands:
          - show version
          - show ip int brief
      register: output

    - name: Print command outputs
      ansible.builtin.debug:
        var: output.stdout_lines


//출력 부분을 아래와 같이 나눠서 출력 가능
    - name: Print command outputs 'sh version'
      ansible.builtin.debug:
        var: output.stdout_lines[0]

    - name: Print command outputs 'sh ip int br'
      ansible.builtin.debug:
        var: output.stdout_lines[1]

        
