---
- name: Get ARP information
  hosts: all
  gather_facts: no

  tasks:
    - name: Show arp table
      ansible.netcommon.cli_command: #해당 컬렉션 이미 설치 되어 있음
        command: show arp
      register: result

    - name: Result of show arp command
      ansible.builtin.debug:
        var: result.stdout_lines