---
- name: Get MAC address table information
  hosts: switches
  gather_facts: no

  tasks:
    - name: Show MAC address table
      cisco.ios.ios_command:
        commands:
          - show mac address-table
      register: result

    - name: Result of show mac address-table command
      ansible.builtin.debug:
        var: result.stdout_lines
