---
- name: Get ARP information
  hosts: gns3
  gather_facts: no

  tasks:
    - name: Show arp table
      cisco.ios.ios_command:
        commands:
          - show arp
      register: result

    - name: Result of show arp command
      ansible.builtin.debug:
        var: result.stdout_lines
