---
- name: Show version and Show ip int br
  hosts: routers
  gather_facts: no

  tasks: #한번에 하나의 명령어씩 처리
    - name: Run 'show version' command
      cisco.ios.ios_command:
        commands: show version
      register: result_version

    - name: Print 'show version' output
      ansible.builtin.debug:
        var: result_version.stdout_lines

    - name: Run 'show ip int brief' command
      cisco.ios.ios_command:
        commands: show ip int brief
      register: result_ip

    - name: Print 'show ip int brief' output
      ansible.builtin.debug:
        var: result_ip.stdout_lines
