- name: Backup show version and other user level commands
  hosts: all
  gather_facts: no
  connection: local #Ansible이 설치된 로컬(제어) 호스트에서 작업 수행

  tasks:
    - name: Run multiple commands on remote nodes
      ansible.netcommon.cli_command:
        command_string:
          - show version
      register: output

    - name: Debug print output
      ansible.builtin.debug:
        var: output.stdout_lines

    - name: Save output to a file
      ansible.builtin.copy: #파일 복사 모듈
        content: "{{ output.stdout[0] }}" #복사할 파일의 내용을 지정
        dest: "./output/{{ inventory_hostname }}.txt" #원격 위치 지정
