---
- name: Backup show version
  hosts: all
  gather_facts: no

  tasks:
    - name: Run single command on remote nodes
      ansible.netcommon.cli_command:
        command_string: show version
      # 안될경우 사용
      # ios_command:
      #  commands: show version
      register: output

    - name: Debug print output
      ansible.builtin.debug:
        var: output.stdout_lines

    - name: Save output to a file
      ansible.builtin.copy: #파일 복사 모듈
        content: "{{ output.stdout[0] }}" #복사할 파일의 내용을 지정
        dest: "./output/{{ inventory_hostname }}.txt" #원격 위치 지정

