---
- name: Get MAC address table information
  hosts: all
  gather_facts: false

  tasks:
    - name: Show MAC address table
      ansible.netcommon.cli_command: #해당 컬렉션 이미 설치 되어 있음
        command: show mac address-table
      register: result

    - name: Result of show mac address-table command
      ansible.builtin.debug:
        var: result.stdout_lines