---
- name: Show version and Show ip int br
  hosts: all
  gather_facts: no

  tasks:
    - name: Run multiple commands on remote nodes
      ansible.netcommon.cli_command:
        command: "{{ item }}"
      loop:
        - show version
        - show ip int brief
      register: result

    - name: Print output
      ansible.builtin.debug:
        var: result.stdout_lines
