- hosts: gns3
  gather_facts: no
  tasks:
    - name: Check if user {{ user }} exists
      cisco.ios.ios_command: #ansible.netcommon.cli_command: 사용 권장
        commands:
          - show running-config | include username
      register: result

    - name: Show the result
      debug:
        var: result.stdout_lines
