---
- hosts: switches
  gather_facts: no
  vars:
    user: ansible2
  tasks:
    - name: Check if user {{ user }} exists
      cisco.ios.ios_command:
        commands:
          - "show run | in username {{ user }}"
      register: result

    - name: Show the user and the result
      debug: #파라미터 수정 : var -> msg
        msg:
          - "User: {{ user }}"
          - "Result: {{ result.stdout_lines }}"
